# Generated by Django 4.2.2 on 2023-06-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(upload_to='fotografias/'),
        ),
    ]
