# Generated by Django 4.2.2 on 2023-06-28 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicada_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
