# Generated by Django 4.2.2 on 2023-06-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_rename_data_publicacao_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={},
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
